### ISSUE TITLE
Why you steal the T3D name? It's an unreal 97 format.

### ISSUE THREAD

**Issue by chaosesqueteam** [RichardRanft/T3DKeyMapMod#1]
Yea why bro? For dis buuuuulllsht? Why bro, fking why.
This sht isn't even 3d sht...

or.. if it is...
Cud you help us implement real T3D from HOOOT 97 (1997) 
in our project? 

Bro.
Anyway the issue is you... RENAME U FKIN EVERYTHING T3d Is UnReAL'S

**Comment by RichardRanft** [comment]
I didn't "steal" the T3D name.  This is a C# tool written **SPECIFICALLY TO MODIFY A FILE IN** Torque 3D.  I haven't looked to see if this file still exists in the newest version of T3D.  If you look at the file dates, it's OBVIOUS that I haven't updated this in YEARS and so it may need to be modified to manage key mapping indexes in the current version of T3D.

Thanks for your attention.  Closing this as completely irrelevant.

**Comment by chaosesqueteam** [comment]
Unreal's T3d predates your t3d. Yea you stole it.
