### ISSUE TITLE
Yea you fking stole the t3d name

### ISSUE THREAD

**Issue by chaosesqueteam** [RichardRanft/T3DKeyMapMod#3]
I saw Torque come, and I saw Torque go.
Yes microsoft did steal that format extension.
Just as you stole the t3d name.

"The Torque family of engines have used the .cs extension for their scripts for a long time. Then Microsoft came along and made C#, using the .cs extension for C# source files. "Oh no! Microsoft stole my format extension!""

This is correct: Microsoft stole that extension.
Just as you stole t3d name.

**Comment by chaosesqueteam** [comment]
Why do you think I'm not inclined to read? I read cases all the time.
You trying to diss me because I disagree with your blatant theft of the venerable .t3d model format name?
With your newer, less venerable, knockoff 3d engine garbage?

**Comment by chaosesqueteam** [comment]
>  This project isn't a game engine.

I remeber Torque3d being announced on slashdot. So don't pretend I don't know what bullshit you're talking about.
The fact is t3d is unreal's. I have to sift through 100s of torque3d bullshit because you fucks were too lazy to type a few more letters, and too ignorant of the history of 3d.

Unreal was the first widespread 3d game engine with coloured lighting.
You spit on it by associating your later also-ran torque 3d bullshit engine. Which came. Which went.
t3d is Unreal's

**Comment by RichardRanft** [comment]
Again, I didn't "steal" anything.  **THIS PROJECT IS NOT A GAME ENGINE**.

This is a utility for use with the T3D game engine - Torque 3D.  It's a Torque 3D key map modifier, hence the name "T3DKeyMapMod".  Is that clear enough?

**Comment by RichardRanft** [comment]
Here - https://torque3d.org - the official site, and Jeff, on the Steering Committee, is a good point of contact.
Go tell them that this project is "stealing" T3D.

**Comment by RichardRanft** [comment]
While you're at it, please contact Epic too - epicgames.com/site/en-US/infringement
