### ISSUE TITLE
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.

### ISSUE THREAD

**Issue by chaosesqueteam** [RichardRanft/T3DKeyMapMod#4]
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.

Thank you for considering our plea, and we look forward to your valuable contribution.

(relevant files: model_brush.c, relevant function: void T3d_Attempt_Which_will_Mod_OBJ_Load(dp_model_t *mod, void *buffer, void *bufferend)

**Comment by RichardRanft** [comment]
Once again - **this project has nothing to do with the .t3d file format**.  I have no knowledge relating to the .t3d file format and I have no interest in changing that.

This project is a **utility** for use with the **Torque 3D Game Engine**.  It modifies the editor scripts to make it easier to find and update game key mappings.
